#!/usr/bin/env bash
#this script that displays the content of the file /etc/passwd.
fileName="/etc/passwd"
while IFS= read -r username userid homedir
do
	echo "$username:$userid:$homedir"
done < $fileName

