#!/usr/bin/env bash 
# this script gives you information about the school file
if [ -e school ] 
then 
	echo "school file exists"
elif [ ! -e school ]
then
	echo "school file does not exist"
elif [ -s school ]
then
	echo "school file is empty"
elif [ ! -s school ]
then
	echo "school file is not empty"
elif [ -f scholl ]
then
	echo "school file is a regular file"
else
	echo ""
fi
