#!/usr/bin/env bash
# display i am invicible!! SIGTERM AND sleep2 

file="/var/run/myscript.pid"
touch $file > "$BASHPID"
while true
do
	echo "To infinity and beyond"
	trap "echo I hate the kill command ; rm $file ; exit " SIGTERM 
	trap "echo Y U no love me?! ; rm $file ; exit " SIGINT 
done

