#!/usr/bin/env bash
# display i am invicible!! SIGTERM AND sleep2 

file="/var/run/myscript.pid"
touch $file > "$BASHPID"
while true
do
	echo "To infinity and beyond"
	trap "echo I hate the kill command" SIGTERM 
	trap "echo Y U no love me?!" SIGINT 
done

